language: python

matrix:
  include:
  - python: '2.6'
  - python: '2.7'
  - python: '3.3'
  - python: '3.4'
  - python: '3.5'
    env: BUILD_DOCS=yes BUILD_INSTALLER=yes STREAMLINK_INSTALLER_DIST_DIR=$TRAVIS_BUILD_DIR/dist/nsis

before_install:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install -r dev-requirements.txt

install:
  - python setup.py install

script:
  - python -m pytest tests/
  - if [[ $BUILD_INSTALLER == 'yes' ]]; then ./script/makeinstaller.sh; fi


addons:
  apt:
    packages:
    - nsis

deploy:
  - provider: releases
    api_key: "${RELEASES_API_KEY}"
    file: "${STREAMLINK_INSTALLER_DIST_DIR}/streamlink-${TRAVIS_TAG}.exe"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD_INSTALLER = yes
  - provider: script
    script: python script/github_releases.py
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD_INSTALLER = yes
