name: Test, build and deploy

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: '0 0 * * *'

env:
  STREAMLINK_DIST_DIR: ${{ github.workspace }}/dist
  SIGNING_KEY_ID: 2E390FA0
  SIGNING_KEY_FILE: ${{ github.workspace }}/signing.key
  DOCS_KEY_FILE: ${{ github.workspace }}/id_rsa_docs

jobs:
  release:
    name: New release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --depth=300 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          ./script/install-dependencies.sh
          python -m pip install -r docs-requirements.txt
          python -m pip install --upgrade Jinja2 wheel twine
      - name: Build shell completions
        run: ./script/build-shell-completions.sh
      - name: Build man page
        run: make --directory=docs man
      - name: sdist and wheels
        run: ./script/build-and-sign.sh
      - name: Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./script/github-release.py "${STREAMLINK_DIST_DIR}"/*.tar.gz{,.asc}
